name: Validate PR
on:
  pull_request:
jobs:
  static_checks:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.2
      - name: Bootstrap
        run: |
          make bootstrap
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run checks
        run: make check-all
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.28.0
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: "-no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
